### ISSUE TITLE
UniSpec with QE charge 1 predictions not supported

### ISSUE THREAD

**Issue by yangkl96** [wilhelm-lab/koina#110]
Hello,

Thanks for supporting UniSpec, I'm very excited to try it! I ran into an issue where peptides with charge 1 and instrument QE  are not supported. Sending it via curl results in the following error:
`{"error":"Failed to process the request(s) for model instance 'UniSpec', message: UnboundLocalError: local variable 'cf' referenced before assignment\n\nAt:\n  /models/repo/UniSpec/1/model.py(38): NCE2eV\n  /models/repo/UniSpec/1/model.py(308): rawinp2tsr\n  /models/repo/UniSpec/1/model.py(496): execute\n`

What is the reason charge 1 cannot be predicted on QE? Would you recommend setting peptides with charge 1 to have instrument = NONE as a workaround?

Best,
Kevin

**Comment by LLautenbacher** [comment]
Hi Kevin,

Thank you for trying out UniSpeci! @jlapin1 worked on the implementation of UniSpec. He can tell you if it's a bug in Koina or if there is a reason why Charge 1 is not supported.
As far as I know adding `instrument=None` would turn off NCE calibration and use raw eV values directly. You should be cautious with that.

**Comment by jlapin1** [comment]
Hey Kevin, its Joel. Very glad you are already trying to use the model. I had intended to contact you directly about it because I knew it was potentially of interest to you and your work.

Our model is trained to to take input of eV, since NCE is inconsistent between machines. Qian Dong (@qdong3161) originally did the painstaking work in finding the regression equations to convert NCE to eV, based on machine and charge. She does not have an equation for charge +1 on machines QE, QEHFX, and ELITE, probably because there was not enough data to find such an equation (there is a regression equation for +1 LUMOS though). My advice is to just set the instrument to None, and accept that the energy being input is likely not ideal.

In case you are interested, the code that does the NCE -> eV conversion is in the file Koina/models/UniSpec/UniSpec/1/model.py in the subroutine NCE2eV on line 8.
