### ISSUE TITLE
limit of batch size

### ISSUE THREAD

**Issue by heejongkim** [wilhelm-lab/koina#115]
Hello,

thank you so much sharing such a great framework to consolidate and streamline the prediction pipeline.
As I'm trying to implement in-house prediction workhorse, I got into a situation how much I can speed up by batching the peptide sequences at once without breaking the model. I tried my best but I don't see much of those recommendation or benchmark for it. Do you have a general suggestion or estimation? Also, are there any parameters I need to adjust based on CPU and GPU memory sizes?

Thank you.

best,
heejong

**Comment by LLautenbacher** [comment]
Hi,
Thanks for reaching out! The batch size you can support depends on the model & the GPU (VRAM) you are using. We developed Koina on a GTX 1080 with 8 GB of VRAM. With the current batch size, we tried to balance stability and performance (for this amount of VRAM). If you increase the batch size, you will reach a point where calls to one model work fine, but concurrent calls to multiple models can cause the service to crash.

Without knowing more about which model you want to optimize, which hardware you want to run it on, and how you use it, any recommendations are tricky.

Best,
Ludwig

**Comment by heejongkim** [comment]
Hi Ludwig,

Thanks for the explanation.
I'm currently testing with one A100 80G VRAM with 1000 peptides and 10,000 peptides in one batch. It seems regardless of batch size, it's at 1-2 second per 1000 peptides if I understood correctly. Also, the gpu core usage only hits 4% with that. I'm not sure what's the best way to parallelize the model to speed up more than what I observed. Should I just fire up more docker container within single gpu until it hits the max memory or I should only have one container per gpu?
Thank you.

best,
heejong

**Comment by LLautenbacher** [comment]
We haven't tested yet how multiple containers on one GPU behave under heavy load. They might get into each others way.
One thing you can try out is to increase the instance group setting of the models 

```
```

**Comment by LLautenbacher** [comment]
We have yet to test how multiple containers on one GPU behave. They might get into each other's way, and you would need to run a load balancer to distribute the load between the containers. But it is probably the easiest option to increase performance.
It's surprising that you see the same performance regardless of batch size. We observed that performance improves with increasing batch size. Did you increase the batch size of all models or only the main ensemble? In the latter case, your observation would make sense since Koina internally splits the requests into batches of 1000 to adhere to the limits of the "sub-models".

You could also try to increase the `count` within the `instance_group` setting of the model (see below). You would also need to do this for every part of the pre-and postprocessing step of the model. Considering your GPU, the core model is likely not the limiting factor. Increasing the count of pre- and postprocessing instances should give you a bigger performance boost.

```
  instance_group [
    {
      count: 2
      kind: KIND_GPU
    }
  ]
```

**Comment by heejongkim** [comment]
Thank you so much for your explanation.

So, basically I need to get inside of the container and manually edit the config file for each model?
For example, if I were to use this model, AlphaPeptDeep_ms2_generic, then I need to edit the following?
https://github.com/wilhelm-lab/koina/blob/d72be952c991ec27258edc9b7319329b6f391edb/models/AlphaPept/AlphaPeptDeep_ms2_generic/config.pbtxt

Also, in this particular case, I don't see the instance_group while I see it in other model config files. I wonder it's because the framework is designed around this model so pre-/post-processing is bypassed?

Thank you so much.

best,
heejong

**Comment by LLautenbacher** [comment]
Yes, that's why the easier option is to spawn multiple containers on the same GPU and host a separate load balancer. To check how they would interact with each other. Increasing the batch size for each model is, for sure, a more manual approach, but it is almost guaranteed to be more stable.

The reason you don't see instance groups for this model is that the config is autocompleted to fill this in.
Here is the autocompleted instance_group config:

```
"instance_group": [
{
"name": "AlphaPeptDeep_ms2_generic",
"kind": "KIND_GPU",
"count": 1,
["gpus"](https://koina.proteomicsdb.org/v2/models/AlphaPeptDeep_ms2_generic/config): [
0
],
"secondary_devices": [],
"profile": [],
"passive": false,
"host_policy": ""
}
],
```

**Comment by heejongkim** [comment]
Thank you for your explanation.
I changed the batch_size from 1000 to 10000 for all AlphaPept config.pbtxt inside of the container that I'm currently using and found no performance boost so I would like to try the instance_group count parameter. Unfortunately, I'm having a little bit of issue to locate where to go to change the setting to tweak the autocompleted config for AlphaPept. I would really appreciate if you can guide me where to look for and what to change.
Thank you so much.

best,
heejong

**Comment by LLautenbacher** [comment]
Since there are different autocomplete behaviors per backend, I don't think there is a central place to adjust default values or the general autocomplete behavior. You would need to adjust this for every model individually.
