### ISSUE TITLE
OpenAPI document doesnt adhere to standard

### ISSUE THREAD

**Issue by tkschmidt** [wilhelm-lab/koina#117]
Hey :),

the provided document at https://koina.wilhelmlab.org/openapi.yml is not OpenAPI 3.3 compatible. I have checked the content at https://editor.swagger.io/ and also tried to use the official openAPI generator, e.g. `openapi-generator generate -g python -i https://koina.wilhelmlab.org/openapi.yml`.

It seems that it needs at least a version within the `info` section but throws more warnings for other areas.

**Comment by LLautenbacher** [comment]
Thanks for spotting this! I think this was broken since the latest rework of the openapi generation script. 
It's going to be fixed once ceb7e6d7ca99ed33d6a325bcd2b0594ffb96314b is merged. 
In the meantime, here is the fixed version: [openapi.yml.zip](https://github.com/user-attachments/files/17074754/openapi.yml.zip)
This version doesn't show any errors with https://editor.swagger.io/.
